# Generated by Django 5.0.7 on 2024-08-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPsihHelpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(choices=[('problems in relationsheep', 'проблемы в отношениях'), ('work/study', 'проф деятельность - учеба/работа'), ('emotionale condition', 'эмоциональное состояние'), ('another', 'другое'), ('do not want to say', 'не хочу говорить')], max_length=100)),
                ('psih_gender', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('does not metter', 'без разницы')], max_length=15)),
                ('psih_years_old', models.CharField(choices=[('25', '25 лет'), ('25-35', '25-35 лет'), ('35-45', '35-45 лет'), ('45-55', '45-55 лет'), ('55', 'от 55 лет'), ('does not metter', 'без разницы')], max_length=20)),
                ('price', models.CharField(choices=[(3000, '3-х лет - от 3.000 рублей'), (4000, 'middle - от 4.000 рублей'), (5000, 'ведущий психолог с опытом от 5 лет - от 5.000 рублей')], max_length=100)),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
