# Generated by Django 5.0.7 on 2024-09-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblems_and_Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(choices=[('problems in relationsheep', 'Проблемы в отношениях'), ('work/study', 'Проф деятельность - учеба/работа'), ('emotionale condition', 'Эмоциональное состояние'), ('another', 'Другое'), ('do not want to say', 'Не хочу говорить')], max_length=100)),
                ('comment_ab_problem', models.CharField(max_length=255)),
                ('prefer_psih_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ("doesn't metter", 'Не важно')], max_length=15)),
                ('prefer_psih_years_old', models.CharField(choices=[('25', '25 лет'), ('25-35', '25-35 лет'), ('35-45', '35-45 лет'), ('45-55', '45-55 лет'), ('55', 'от 55 лет'), ("doesn't metter", 'без разницы')], max_length=20)),
                ('prefer_price', models.CharField(choices=[('3000', '3-х лет - от 3.000 рублей'), ('4000', 'middle - от 4.000 рублей'), ('5000', 'ведущий психолог с опытом от 5 лет - от 5.000 рублей'), ("doesn't metter", 'Не важно')], max_length=100)),
                ('prefer_time_slots', models.CharField(max_length=255)),
                ('prefer_notif', models.CharField(choices=[('email', 'Email'), ('SMS', 'SMS')], max_length=255)),
                ('prefered_method_for_chatting', models.CharField(max_length=511)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
