# Generated by Django 5.0.7 on 2024-09-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproblems_and_preferences',
            old_name='prefered_method_for_chatting',
            new_name='prefered_method_for_chating',
        ),
    ]
