"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and thei0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qn7d_yfykvabmbkvc6mrkss+b6l#16x-sg76punvy&1(*-j2a^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'zeldinvasya@gmail.com'
EMAIL_HOST_PASSWORD = 'mudh pfqo iwjv nfgl'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

MEDIA_ROOT = os.path.join(BASE_DIR, 'frontend/files')
MEDIA_URL = '/files/'


# Application definition
SITE_ID = 1
INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'client_page',
    'main_page',
    'psihologist_page',
    'chat',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.vk',
    'allauth.socialaccount.providers.yandex',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #allauth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'frontend/html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/frontend/static/'
STATICFILES_DIRS = [
    BASE_DIR / "frontend/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/additionaly-info/'

# ACCOUNT_FORMS = {'signup': 'registration_page.forms.CustomSignupForm'}
# ACCOUNT_TEMPLATES = {'signup': 'sign_up_social.html'}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }, 
    'yandex': {
        'SCOPE': [
            'login:email', 
            'login:info',
        ],
    },
    # 'vk': {
    #     'APP': {
    #         'client_id': '52053732',
    #         'secret': 'ZQkIRTmOyZmGw3l91Nch',
    #     },
    #     'SCOPE': [
    #         'email',
    #         'first_name',
    #         'last_name',
    #     ],
    #     'AUTH_PARAMS': {
    #         'v': '5.131'
    #     }
    # }
}

SUBSCRIBE_PRICE = {
    "1 session": {
        "price": 3000,
        "sessions": 1,
        "duration": 0,
        "privilege": [
            "Доступ к одному занятию",
            "Возможность выбрать психолога из доступных"
        ]
    },
    "1 month": {
        "price": 11000,
        "sessions": 4,
        "duration": 30,
        "privilege": [
            "Доступ к четырем занятиям",
            "Возможность выбрать психолога из доступных"
        ]
    },
    "3 months": {
        "price": 34000,
        "sessions": 12,
        "duration": 90,
        "privilege": [
            "Доступ к двенадцати занятиям",
            "Более выгодная стоимость за занятие",
            "Возможность выбрать психолога из доступных"
        ]
    },
    "6 months": {
        "price": 58000,
        "sessions": 20,
        "duration": 180,
        "privilege": [
            "Доступ к двадцати занятиям",
            "Более выгодная стоимость за занятие",
            "Возможность выбрать психолога из доступных",
        ]
    },
    "1 year": {
        "price": 110000,
        "sessions": 40,
        "duration": 365,
        "privilege": [
            "Доступ к сорока занятиям",
            "Самая выгодная стоимость за занятие",
            "Возможность выбрать психолога из доступных",
        ]
    }
}
