# Generated by Django 5.0.7 on 2024-07-31 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Бакалавр', 'bachelor'), ('Специалист', 'specialist'), ('Магистр', 'master')], max_length=50)),
                ('universyty', models.CharField(max_length=100)),
                ('diploma', models.FileField(upload_to='files')),
                ('training', models.CharField(max_length=100)),
                ('advanced_curses', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('science_interestings', models.CharField(max_length=500)),
                ('achievements', models.CharField(max_length=200)),
                ('work_area', models.CharField(max_length=100)),
                ('often_questions', models.CharField(max_length=200)),
                ('experience', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2)),
                ('something_to_add', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihologist_page.summary')),
            ],
        ),
    ]
