# Generated by Django 5.0.7 on 2024-08-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('clients_count', models.CharField(help_text='You can write an intervele', max_length=100)),
                ('online_expirience', models.BooleanField()),
                ('self_terapy', models.BooleanField()),
                ('supervisore_have', models.BooleanField()),
                ('supervisore_recomindation', models.FileField(upload_to='')),
                ('additional_work_studing', models.CharField(max_length=100)),
                ('clients_count_on_platform', models.CharField(help_text='You can write an intervele', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField()),
                ('referal', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Бакалавр', 'bachelor'), ('Специалист', 'specialist'), ('Магистр', 'master')], max_length=50)),
                ('facs', models.CharField(max_length=100)),
                ('universyty', models.CharField(max_length=100)),
                ('diploma', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='FreePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_places', models.CharField(max_length=4700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=4700)),
                ('psih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psih', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_session', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_study', models.CharField(max_length=200)),
                ('additional_studing', models.CharField(max_length=100)),
                ('expirience', models.IntegerField()),
                ('practise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihologist_page.practise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('universyty', models.ManyToManyField(to='psihologist_page.universyty')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psihologist_page.summary')),
            ],
        ),
    ]
