# Generated by Django 5.0.7 on 2024-08-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psihologist_page', '0002_subscribesprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribesprice',
            name='per_3_months',
        ),
        migrations.RemoveField(
            model_name='subscribesprice',
            name='per_half_year',
        ),
        migrations.RemoveField(
            model_name='subscribesprice',
            name='per_month',
        ),
        migrations.RemoveField(
            model_name='subscribesprice',
            name='per_year',
        ),
    ]
