# Generated by Django 5.0.7 on 2024-08-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psihologist_page', '0002_alter_sessionsdate_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionsDate',
        ),
    ]
