# Generated by Django 5.0.7 on 2024-08-20 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihologist_page', '0003_delete_sessionsdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=4700)),
                ('psih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psih', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
