# Generated by Django 5.0.7 on 2024-08-04 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psihologist_page', '0004_freeplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeplaces',
            name='free_places',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None),
        ),
    ]
