# Generated by Django 5.0.7 on 2024-07-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_page', '0002_emailconfirmation_delete_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='code',
            new_name='token',
        ),
    ]
