# Generated by Django 5.0.7 on 2024-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_page', '0003_rename_code_emailconfirmation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('specialyty', models.CharField(choices=[('psihologyst', 'PSIHOLOGYST'), ('regular user', 'REGULAR USER')], default='regular user', max_length=12)),
                ('profile_picture', models.ImageField(upload_to='images')),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
