# Generated by Django 5.0.7 on 2024-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='subscribe',
            field=models.CharField(choices=[('none', None), ('1 session', '1 session'), ('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], default=('none', None), max_length=100),
        ),
    ]
