# Generated by Django 5.0.7 on 2024-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='specialyty',
            field=models.CharField(choices=[('psihologist', 'PSIHOLOGYST'), ('regular_user', 'REGULAR USER')], default='regular_user', max_length=100),
        ),
    ]
