# Generated by Django 5.0.6 on 2024-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessages',
            name='content',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
