# Generated by Django 5.0.7 on 2024-08-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_userinformation_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='date_expired',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='subscribe',
            field=models.CharField(choices=[(None, 'none'), ('1 session', '1 session'), ('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], default=(None, 'none'), max_length=100),
        ),
    ]
