# Generated by Django 5.0.7 on 2024-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_userinformation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='specialyty',
            field=models.CharField(choices=[('regular_user', 'REGULAR USER'), ('psihologist', 'PSIHOLOGYST')], default='regular_user', max_length=100),
        ),
    ]
