# Generated by Django 5.0.7 on 2024-08-03 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_userinformation_date_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_expired',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
