# Generated by Django 5.0.7 on 2024-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_userinformation_specialyty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='specialyty',
            field=models.CharField(choices=[('regular user', 'REGULAR USER'), ('psihologist', 'PSIHOLOGYST')], default='regular user', max_length=100),
        ),
    ]
