# Generated by Django 5.0.7 on 2024-08-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_userinformation_date_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='date_expired',
        ),
    ]
