# Generated by Django 5.0.7 on 2024-08-04 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_remove_userinformation_date_expired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='subscribe',
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.CharField(choices=[(None, 'none'), ('1 session', '1 session'), ('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], default=(None, 'none'), max_length=100)),
                ('duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
