# Generated by Django 5.0.7 on 2024-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_userinformation_subscribe_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='sessions_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
