# Generated by Django 5.0.7 on 2024-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_subscribe_sessions_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='expirience',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='time_zone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
