# Generated by Django 5.0.7 on 2024-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_userinformation_expirience_userinformation_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='about',
            field=models.CharField(default='fuck you', max_length=255),
            preserve_default=False,
        ),
    ]
